### ISSUE TITLE
Android Issue - After sharing the proof of request the BCSC account did not open

### ISSUE THREAD

**Issue by DImalika** [bcgov/bc-wallet-mobile#639] opened 2022-10-12 21:24 UTC
Repro Steps:
-Receive and accept the BVVC pilot credential
-Select BC Digital ID button
-Select "Share" on Proof of request

Expected Result:
In app browser opens the BCSC Account review page.

Actual Result:
-Navigated back to home page and did not open the BCSC Account review page.
-BC Digital ID button is disabled
-Mapped to IASP-14566

Notes:
Android 1Plus 7 OS 11
BC Wallet build version 404

**Comment by nodlesh** [comment] 2022-10-13 18:09
Closing as duplicate of #629

**Closed as completed by nodlesh** 2022-10-13 18:09 UTC
