### ISSUE TITLE
Glitchy behaviour when resuming the app after timeout

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1190] opened 2023-06-15 16:56 UTC
### Description of problem
Then the app timeout (for inactivity or being on the backgroud), after re-unlocking the app, the app is a bit glitchy where scanning a QR code for credential offer or proof request just doesn't work, I can't accept the proof request

### Environment
- [ ] Occurs on Android
- [x] Occurs on iOS

Build #:

Android Device Model: 

iOS Device Model: 

### Severity
- [ ] High
- [ ] Medium
- [ ] Low

**Comment by wadeking98** [comment] 2023-07-13 23:22
Tested with latest from main and cannot reproduce. @cvarjao can you please confirm if this is still an issue?

**Comment by hiteshgh** [comment] 2023-07-17 21:41
not able to re-produce , closing for now , if issue re-occurs will create a new ticket

**Closed as completed by hiteshgh** 2023-07-17 21:41 UTC
