### ISSUE TITLE
1024 error when getting the Person credential

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#2026] opened 2024-06-21 16:40 UTC
### Description of problem
While attempting to get a Person credential, this individual saw a 1024 error message (see screenshot). An reinstall of their wallet did not help. 

Afterwards, they saw a "Cannot create credential" error message within the id.gov.bc.ca webview.

### Steps to reproduce

1. this individual had an existing and active BCSC app.
2. they downloaded the wallet and then attempted to get their person cred.
3. they were using an Android device with Chrome browser (apologies versions were not captured).
4. wifi was turned off and cell data on (fast.com speeds of 70-80mbps).
5. Step 1 screen prompt (confirming BCSC app setup) would show as being successful.
6. Step 2 screen prompt of getting the person cred is where the process would fail to complete.
7. There was prolonged waiting (spin) with no feedback until failure (observed that when spin is prolonged without feedback user behaviour was to "x" out because they think "it's done" or to "try again").
8. The detailed error message above was hidden under a 1 liner plain language precursor error message that pops up about failing to get the person cred. As part of that message there is a Show Details hyperlink - when that is selected it provides the detailed message above.
9. There was also a firewall error message that came up at a later step once the above error was accepted ("okay") that didn't make sense given 3 above.
10. the switching between Wallet and BCSC on Chrome is not clear (related to 7 above) especially and further compounded when back to back error messages start to occur.
11. As noted above, Wallet uninstall and re-install (from the app store) was completed as the final troubleshooting step and it did not resolve and instead led to the second screenshot.

### Screenshots and/or log output
![image](https://github.com/bcgov/bc-wallet-mobile/assets/68872187/6207f9c7-9a2d-440d-adba-b26583b75b44)

![image](https://github.com/bcgov/bc-wallet-mobile/assets/68872187/4796539f-816f-49af-ad9f-05afdd4fb14a)

### Environment
- [x] Occurs on Android
- [ ] Occurs on iOS

Build #: 1.0.06

Android Device Model: 

iOS Device Model: 

### Severity
- [x] High
- [ ] Medium
- [ ] Low

**Comment by pksmith744** [comment] 2024-06-21 19:50
Please update severity to high as this is an unpredictable production issue at the beginning of the experience which makes this a high candidate for abandonment and negative user experience.  This was 15mins of 1:1 troubleshooting and observation that ended without getting the person cred.

1) this individual had an existing and active BCSC app.
2) they downloaded the wallet and then attempted to get their person cred.
3) they were using an Android device with Chrome browser (apologies versions were not captured).
4) wifi was turned off and cell data on (fast.com speeds of 70-80mbps).
5)  Step 1 screen prompt (confirming BCSC app setup) would show as being successful.
6) Step 2 screen prompt of getting the person cred is where the process would fail to complete.
7) There was prolonged waiting (spin) with no feedback until failure (observed that when spin is prolonged without feedback user behaviour was to "x" out because they think "it's done" or to "try again").
8) The detailed error message above was hidden under a 1 liner plain language precursor error message that pops up about failing to get the person cred.  As part of that message there is a Show Details hyperlink - when that is selected it provides the detailed message above.
9) There was also a firewall error message that came up at a later step once the above error was accepted ("okay") that didn't make sense given 3 above.
10) the switching between Wallet and BCSC on Chrome is not clear (related to 7 above) especially and further compounded when back to back error messages start to occur. 
11) As noted above, Wallet uninstall and re-install (from the app store) was completed as the final troubleshooting step and it did not resolve and instead led to the second screenshot.

As discussed, can we please look at:
- root cause
- decoding the error message
- recreating (if possible)
- resolution steps

**Comment by cvarjao** [comment] 2024-07-09 20:28
This will be fixed by #2023

**Comment by jleach** [comment] 2024-07-10 15:27
Assigned to @bryce-mcmath because he's working on #2023 which will fix this issue as noted above.

**Comment by bryce-mcmath** [comment] 2024-07-29 20:37
Proxy mentioned above is now available in developer settings, hopefully it will help bypass this issue

**Closed as completed** 2024-09-24 17:12 UTC
