### ISSUE TITLE
Connection erroneously being deleted

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1239] opened 2023-07-05 16:26 UTC
After connecting using the verifier "Connection Invitation" feature, the connection gets deleted

### Environment
- [ ] Occurs on Android
- [ ] Occurs on iOS

Build #:

Android Device Model: 

iOS Device Model: 

### Severity
- [ ] High
- [ ] Medium
- [ ] Low

**Comment by wadeking98** [comment] 2023-07-14 20:34
I can't reproduce this on main

**Comment by hiteshgh** [comment] 2023-07-17 21:42
assigned to @wadeking98 to confirm if this was tested in " Test flight " and if working close it

**Comment by nodlesh** [comment] 2023-07-26 20:26
Cannot reproduce in build 1087.

**Closed as completed** 2023-08-22 17:01 UTC
