### ISSUE TITLE
error getting person credential (2033 - invalid params)

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#2041] opened 2024-06-27 21:46 UTC
### Screenshots and/or log output

![signal-2024-06-27-144350](https://github.com/bcgov/bc-wallet-mobile/assets/1348549/06c29a93-014f-430e-b1e6-80fd48274430)

![signal-2024-06-27-144354](https://github.com/bcgov/bc-wallet-mobile/assets/1348549/07520b6e-b230-4e00-8539-e3d5542bc31c)

### Environment
- [ ] Occurs on Android - works on Android
- [x] Occurs on iOS

Build #: 1.0.18-1771

Android Device Model: 

iOS Device Model: 

### Severity
- [x] High
- [ ] Medium
- [ ] Low

**Comment by jleach** [comment] 2024-06-27 23:18
This was caused by a bug in our attestation controller v2 (recent refactoring). It only impacts BC Wallet v1.0.18. Fixed in the attestation controller via PR bcgov/mobile-attestation-vc-controller#62.

**Comment by knguyenBC** [comment] 2024-07-08 23:42
tested on iOS (iPhone SE, 17.5.1) and Android (pixel 8, android 14).

**Comment by jleach** [comment] 2024-07-10 15:25
Verified in 1.0.18.

**Closed as completed by jleach** 2024-07-10 15:25 UTC
