### ISSUE TITLE
Fix delay in first credential issuance

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#387] opened 2022-06-06 21:59 UTC
There's a long delay (about 1 minute?) in the credential issuance that renders people thinking that the wallet is not frozen.

What can be offloaded to the application initialization process? Maybe machine readable governance?
What elements needs to be warmed up?
- Schema
- Credential Definition
- Revocation Registry
- Tails file
- Revocation Registry Entry

What sort of feedback can we provide to the user

Maybe we can make the ledgers configurable by BC Wallet and we can delivery BC Wallet with a very small subset of ledgers

**Comment by nodlesh** [comment] 2022-12-07 16:28
From the Nightly regression tests there is no real decernable performance increase on the first credential issuance or credential issuance in general. There are times it looks like a 10-20% increase but other runs are the same or longer as previous builds without the enhancement. 

Do we want to close this and track further enhancements in other issues or move this to the backlog? @amanji @cvarjao

**Comment by amanji** [comment] 2022-12-07 16:37
Is it possible in the test environment that ledgers are completely loaded before the credential exchange is initiated?  

The key issue to confirm is whether not having complete ledger connections by the first credential exchange results in the delay.

**Comment by knguyenBC** [comment] 2023-01-19 17:50
Retest this issue and provide more details. Possible make this an epic to include other errors that involve the credential issuance delay.

**Closed as completed** 2023-03-20 17:15 UTC
Labels: enhancement, spike
