### ISSUE TITLE
Improve the no internet/firewall banner

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1772] opened 2024-02-06 18:41 UTC
### Background
As a person using the BC Wallet, I want to know if there's the internet is poor or non-existent so that I can properly troubleshoot the issue I'm experiencing.

As a developer of the BC Wallet app, I want to be able to filter out issues with the wallet that have anything to do with poor internet connection so that I can focus on actionable issues

**UI Improvements**
The banner that appears when no internet connection is detected or when a firewall is detected covers key UI elements in the header (ex. the back button). Some people have a hard time figuring out how to dismiss the banner. 

It goes away on its own and sometimes comes back and when people have tried interacting with it, it has gotten stuck.

We also have reports of people seeing the notification and not understanding its purpose.

UX Improvements
- Explore improving the messaging
- expand the purpose of this banner to include reporting poor internet connection

### Screenshots
![Image](https://github.com/bcgov/bc-wallet-mobile/assets/68872187/d6928841-ede4-402b-b64c-39c2990b3d57)
![Image](https://github.com/bcgov/bc-wallet-mobile/assets/68872187/c04b8547-998a-4e10-9f53-eb540d8d89aa)

**Comment by jleach** [comment] 2024-06-19 20:43
Tried a few things. Updating the ledger nodes (genesis block) and manually confirming the results from some BC Wallet debugging. The wallet is getting a "timeout" on most of the ledger nodes. There are one or two that work and this is probably why the test works but its not overly reliable because if that one node can not or does not respond then the firewall message appears. In any case, we need to find a better way to check a node than opening a TCP conneciton to it on the client_ip and client_port.

```console
 LOG  connected: 154.0.164.39 9702
 LOG  timeout: 54.207.36.81 9702
 LOG  timeout: 128.130.204.35 9722
 LOG  timeout: 35.167.133.255 9702
 LOG  timeout: 34.226.105.29 9701
 LOG  timeout: 34.224.255.108 9796
 LOG  timeout: 38.70.17.248 9702
```

Confirmed with `nmap -Pn -sT --reason -p 9702 54.207.36.81`

```console
Scanning 54.207.36.81 on ports 9702
Command: nmap -Pn -sT --reason -p 9702 54.207.36.81
Starting Nmap 7.95 ( https://nmap.org ) at 2024-06-19 11:04 PDT
Nmap scan report for ec2-54-207-36-81.sa-east-1.compute.amazonaws.com (54.207.36.81)
Host is up, received user-set.

PORT     STATE    SERVICE REASON
9702/tcp filtered unknown no-response
```

**Comment by cvarjao** [comment] 2024-10-22 18:28
we are removing the firewall checks altogether

**Comment by bryce-mcmath** [comment] 2024-11-05 19:51
Duplicate of #1907, closing

**Closed as completed by bryce-mcmath** 2024-11-05 19:51 UTC
Labels: story/design, needs/ux-wireframe
