### ISSUE TITLE
Can't see "create pin" button in the PIN Screen when using large font size

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#823] opened 2023-01-11 19:37 UTC
When using a very large font size then PIN fields get cut off and I cant navigate/scroll to "confirm PIN" field

Device: iPhone 7 (iOS 15.7.2)

![signal-2023-01-11-113557](https://user-images.githubusercontent.com/1348549/211901740-ba91c3d1-55b8-4dca-929c-7320042f926b.png)

![signal-2023-01-11-113600](https://user-images.githubusercontent.com/1348549/211901769-e99fed86-61bd-446a-93de-6d837c4a53aa.png)

Notes:
- might be useful to use [KeyboardAvoidingView](https://reactnative.dev/docs/keyboardavoidingview) in combination with [ScrollView](https://reactnative.dev/docs/scrollview)

**Comment by cvarjao** [comment] 2023-01-17 19:50
@wadeking98 , let me know when this is a buikd in testflight and I can test it

**Comment by wadeking98** [comment] 2023-01-17 20:19
resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/586
duplicate of: #801

**Comment by nodlesh** [comment] 2023-01-18 20:54
@cvarjao You may want to retest this in build 650, but from my perspective this is still an issue even thought he screen is scrollable. I think we should change the title to "PIN entry not visible with larger text".

**Comment by nodlesh** [comment] 2023-03-29 21:09
This is fixed.

**Closed as completed** 2023-07-17 20:27 UTC
