### ISSUE TITLE
issues with using the wallet after timeout

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1089] opened 2023-05-08 15:46 UTC
At least in iOS, after some idling time and re-authenticating the mobile verifier feature doesn't work as expected.

- Open wallet
- Let it idle until it auto-locks
- unlock app again
- use the verifier

Needs to be re-tested after AFJ 0.4.0

**Comment by bryce-mcmath** [comment] 2023-05-09 17:19
@cvarjao Any more details for this one?

**Comment by wadeking98** [comment] 2023-07-10 19:49
Resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/879

**Comment by hiteshgh** [comment] 2023-07-17 21:34
not able to reproduce , closing, if the issue re-occurs will open a new issue later

**Closed as completed** 2023-07-17 21:34 UTC
