### ISSUE TITLE
Review/Fix console warnings when running locally (metro)

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#2108] opened 2024-08-01 16:31 UTC

**Comment by bryce-mcmath** [comment] 2024-08-15 02:39
Almost all metro log warnings have been fixed, but there is one caused by the onboarding screens changing too quickly which can only be fixed by changing the navigation flow or disabling animation

**Closed as completed by bryce-mcmath** 2024-08-15 02:39 UTC
Labels: Technical Debt
