### ISSUE TITLE
App Attestation (v1) | Activation by Proof Request | development

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1667] opened 2023-12-12 18:40 UTC
## Acceptance Criteria
- When receiving a proof request for app attestation, if there is no app attestation credential that satisfies the proof request, start the process (in the background) to get a new one
- For now, Credential Offer and Proof request will be visible to the user
- Single flow
    - Receive Proof Request
    - check if proof request can be satisfied
    - if not, start attestation
       - wait for credential offer
       - auto-accept attestation offer
       - resume to proof request
     - user can then accept/decline proof request)

## Notes
- Proof request JUST for app attestation
- Proof request WITH app attestation

**Comment by cvarjao** [comment] 2023-12-12 18:56
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BC-Wallet-6148e7423fe04b001444e2bd/issues/bcgov/bc-wallet-mobile/1667?planning-poker) with Zenhub @bryce-mcmath @jleach @wadeking98

**Comment by jleach** [comment] 2024-01-04 17:45
Duplicate of #1661

**Comment by jleach** [comment] 2024-01-04 17:45
- [ ]

**Comment by jleach** [comment] 2024-01-19 15:48
Fixed Apple attestation step 5 as part of bcgov/mobile-attestation-vc-controller#17

**Closed as completed** 2024-09-24 17:03 UTC
