### ISSUE TITLE
Debug issue with Credivera verification

### ISSUE THREAD

**Issue by jleach** [bcgov/bc-wallet-mobile#1788] opened 2024-02-12 16:36 UTC
Debug and fix issue with Credivera's verification in BC Wallet

**Comment by bryce-mcmath** [comment] 2024-03-12 22:12
@jleach what's the status of this ticket? Should we close it? There isn't much in the description

**Comment by jleach** [comment] 2024-03-18 15:34
@bryce-mcmath  It only happens for one person when doing phone-to-phone verification and after looking through the debug logs I can't see anything obvious that is the issue. I think its this issue can sit in a holding pattern to see if it effects other people.

**Comment by knguyenBC** [comment] 2024-04-11 16:38
Can't reproduce. Leave it in needs refinement until more info comes up

**Closed as not planned** 2024-04-25 16:36 UTC
