### ISSUE TITLE
Update project to use yarn rather than npm

### ISSUE THREAD

**Issue by jleach** [bcgov/bc-wallet-mobile#530] opened 2022-08-30 17:16 UTC
It's notably complicated to add packages to the project. It would be good to simplify this and update applicable documentations so that developer productivity increases. I believe much of this can be address by converting the project to use yarn - but a test spike may be required.

**Comment by cvarjao** [comment] 2022-11-24 18:22
duplicate of #281

**Closed as completed by cvarjao** 2022-11-24 18:22 UTC
Labels: Technical Debt
