### ISSUE TITLE
Blank connection screen when scanning QR code from Access to Court Materials

### ISSUE THREAD

**Issue by nodlesh** [bcgov/bc-wallet-mobile#1271] opened 2023-07-19 14:04 UTC
### Description of problem
Scanning a QR code from https://a2a-test.apps.silver.devops.gov.bc.ca/dars/pre-vc-auth/  Enter Using Digital Credential results in a connection screen that is blank.

Note that this wallet does not have a credential that issuer for the credential needed for the proof. Not sure if that is part of the issue. 

### Expected behavior
You would get a proper chat screen with the proof request in the chat messages. 

### Steps to reproduce
Go to https://a2a-test.apps.silver.devops.gov.bc.ca/dars/pre-vc-auth/ 
Select Enter Using Digital Credential 
scan the QR code

### Screenshots and/or log output
![IMG_1B0372326197-1.jpeg](https://images.zenhubusercontent.com/5e3864b3b64bc2429a017886/cd4c71fb-4b94-4621-82b8-28c504c4aa3b)

### Environment
- [ ] Occurs on Android
- [X ] Occurs on iOS

Build #: 1077

Android Device Model: 

iOS Device Model: iPhone 6s iOS 15.7

### Workaround
Go home and select the proof request to continue.

### Severity
- [ ] High
- [ X] Medium
- [ ] Low

**Comment by knguyenBC** [comment] 2023-07-24 23:16
@jleach @nodlesh Is this the same ticket as #1258?

**Comment by nodlesh** [comment] 2023-07-24 23:25
> @jleach @nodlesh Is this the same ticket as #1258?

Yes I believe it is.

**Comment by hiteshgh** [comment] 2023-07-25 17:28
closing , duplicate of #1258

**Closed as completed by hiteshgh** 2023-07-25 17:28 UTC
