### ISSUE TITLE
Unlock Person Credential by Business Card

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1567] opened 2023-10-24 22:12 UTC
Credential Definition IDs:
- https://candyscan.idlab.org/tx/CANDY_PROD/domain/350
- https://candyscan.idlab.org/tx/CANDY_PROD/domain/351

**Comment by jeffaudette** [comment] 2023-12-05 18:30
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BC-Wallet-6148e7423fe04b001444e2bd/issues/bcgov/bc-wallet-mobile/1567?planning-poker) with Zenhub @wadeking98 @jleach @bryce-mcmath

**Comment by jleach** [comment] 2023-12-14 19:40
@cvarjao Is this a circular dependency? To get a business card you need to do something with registry for which I believe a requirement is the person credential. I ask because PW used registries to open a sole proprietorship for which he needed the Person credential. Then he was able to issue a Business Card.

**Comment by cvarjao** [comment] 2023-12-14 19:41
No. People only need BC Services Card App to login to BC Registries. There is NO requirement for Person Credential to get Business Card. Maybe in the future when Person Credential is GA that might change.

**Comment by jleach** [comment] 2023-12-14 19:43
Noted. I must have misunderstood.

**Comment by jleach** [comment] 2023-12-18 18:20
Blocked. Working to get a test site we can use to test this feature. It only works with sole proprietor business and we don't know anyone with access to BC Wallet for testing. Reaching out to the registry team to see if they can help.

**Comment by jleach** [comment] 2023-12-20 00:24
Feature in 1.0.13 Build 1400

**Comment by jleach** [comment] 2023-12-21 02:27
Confirmed fixed by Peter in 1.0.13 1403.

**Closed as completed** 2023-12-21 02:28 UTC
