### ISSUE TITLE
Allow the mediator to be changed when in Developer mode

### ISSUE THREAD

**Issue by jleach** [bcgov/bc-wallet-mobile#1668] opened 2023-12-12 19:01 UTC
It would be handy for debugging purposes if the mediator can be changed on-the-fly when Developer mode is enabled.

**Comment by WadeBarnes** [comment] 2023-12-12 19:11
In the role of SRS/DevOps when working on the mediator services we want an easy and convenient way to test out changes in the various environments.  We typically do not have (or want to have) a wallet development environment at our disposal to test the changes.  Therefore being able to switch between mediators instances through the Developer options of the wallet would be exceptionally helpful for testing and troubleshooting.  Being able to select between `production` and `custom` would be all that's needed.  When selecting `custom` the user would be able to paste in the complete invite URL from the desired mediator.

**Comment by cvarjao** [comment] 2024-01-08 17:51
closing this one as duplicate of #1583

**Closed as not planned** 2024-01-08 17:51 UTC
